### ISSUE TITLE
Plugin slightly slower performance compared to regular gulp

### ISSUE THREAD

**Issue by vHeemstra** [CT1994/gulp-multi-thread-task#1]
Hi,
I tried your plugin for my gulp task that processes images, but found that it was actually slower than without it.. Not sure if I'm doing something wrong, my task is not suitable for multi-threading or that the plugin might have some issue?

**Situation**
I have some directories with JPG, PNG and GIF image files. They have to be converted to WebP and placed besides their original counterpart.

***System***
* PC: Windows 10 on quad core processor
* Node: v14.8.0
* Npm: v6.14.8

***Directory structure***
```
cdn/
    pictures/
         (around 120 .jpg, .png and .gif files, average filesize ~120kB)
    thumbs/
         (around 110 .jpg, .png and .gif files, average filesize ~10kB)
```

***gulpfile.js***
```
const { task, src, dest } = require('gulp');
const {GulpMultiThreadTask} = require('gulp-multi-thread-task');

const gulpimagemin = require('gulp-imagemin'); // For image handling
const imagemin_webp = require('imagemin-webp'); // Converts JPG/PNG to WebP
const imagemin_gif2webp = require('imagemin-gif2webp'); // Converts only GIF to WebP
const rename = require('gulp-rename');

function webpPicturesTask(done, srcGlob) {
  return src(srcGlob, { base: 'cdn/' })
    .pipe(gulpimagemin([
      imagemin_webp({
        lossless: false,
        method: 6,
      }),
      imagemin_gif2webp({
        lossy: false,
        mixed: false,
        minimize: false,
        method: 6,
        multiThreading: true,
      })
    ], {
      verbose: true
    }))
    .pipe(rename({ extname: '.webp' }))
    .pipe(dest('cdn/'))
  ;

task('webpPictures', function(done, srcGlob) {
  return GulpMultiThreadTask(
    'webpPictures',
    ['cdn/{pictures,thumbs}/**/*.{png,jpg,jpeg,gif}'],
    webpPicturesTask
  );
});
```

**Results**
- Run as a normal task, it processed all 231 files in 54 seconds.
- Run in a multi-threaded set-up as above, it did the same in 65 seconds. (Using 4 workers.)
The additional time to spawn the workers at the start was very small (~1 sec), so I'm confused about the additional time it took.

**Any idea what I'm doing wrong or why it is slower?**

**Comment by CT1994** [comment]
Hi there thank you for the feedback.

I have looked into your issue and it seems that gulp-imagemin is using a through2-concurrent which is concurrently running multiple binaries at the same time.

this plugin will not give any benefits since this is already multi threaded.

**Comment by vHeemstra** [comment]
Ok, I figured something of the sort might be happening. Thanks for clearing it up!
